### ISSUE TITLE
Support protobuf v26.0 and above

### ISSUE THREAD

**Issue by C0mbatwombat** [curioswitch/protobuf-jackson#34]
Hope you are well!

Protobuf 26.0 [introduced breaking changes](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0-rc1), specifically the `com.google.protobuf.Descriptors.FieldDescriptor#hasOptionalKeyword` has [been made non-public](https://github.com/protocolbuffers/protobuf/commit/1aeacd4f4eb4e0aa05d6336e2988a565e475e9a0#diff-2228551d02c6661809ca7103db9512eef4c2d01f35556d42316543d92a89edefL1277).

The stacktrace I encounter when initialized a MessageMarshaller is:
```
Caused by: java.lang.IllegalAccessError: class org.curioswitch.common.protobuf.json.ProtobufUtil tried to access method 'boolean com.google.protobuf.Descriptors$FieldDescriptor.hasOptionalKeyword()' (org.curioswitch.common.protobuf.json.ProtobufUtil and com.google.protobuf.Descriptors$FieldDescriptor are in unnamed module of loader 'app')
        at org.curioswitch.common.protobuf.json.ProtobufUtil.hasOptionalKeyword(ProtobufUtil.java:306)
        at org.curioswitch.common.protobuf.json.ProtoFieldInfo.isInOneof(ProtoFieldInfo.java:219)
        at org.curioswitch.common.protobuf.json.DoParse.apply(DoParse.java:373)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:730)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:715)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:622)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:6043)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4055)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3739)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3991)
        at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildOrFindMarshaller(TypeSpecificMarshaller.java:269)
        at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildAndAdd(TypeSpecificMarshaller.java:146)
        at org.curioswitch.common.protobuf.json.MessageMarshaller$Builder.build(MessageMarshaller.java:494)

```

I suppose it should use the `hasPresence()` method, but I am not 100% sure. 

Thank you

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - I have added compatibility in #35 without breaking, probably the next time this happens we will drop support for v3.

Would you be able to try a snapshot to make sure it works for you?

**Comment by C0mbatwombat** [comment]
Thanks for the quick followup, as always! I will test.

Very much a Google thing to do these breaking changes, thankfully they have at least stopped doing that with Guava. I think quite a few people using Armeria are using your library indirectly, and I suppose many use v3. Next time there is a breaking change we can also try to create a PR for you, so you don't have to do all the work yourself. 

I will let you know if #35 fixes it.

**Comment by C0mbatwombat** [comment]
It worked! Thank you. Note that Armeria is also still waiting for the ecosystem to upgrade: https://github.com/line/armeria/issues/5504. It's a mess, as usual with protobuf..

**Comment by chokoswitch** [comment]
Thanks for confirming @C0mbatwombat - I have released 2.6.0 with the fix (somehow matches 26+ :) )

> I think quite a few people using Armeria are using your library indirectly, and I suppose many use v3

Thanks, I guess I was hoping the "next time" is not too soon. But you're right, we would not drop support for v3 while it's still commonly used, notably incompatibility with Armeria is always a deal-breaker.

**Comment by C0mbatwombat** [comment]
I understand and share your frustration :laughing: 
Thanks again, as always.

**Comment by C0mbatwombat** [comment]
Hi @chokoswitch, 

Sorry to keep taking your time, I've tried to update from 2.5.0 -> 2.7.0, but I didn't succeed. The problem is: I was never able to fully update from proto3 -> proto4 because other libraries were not supporting proto 4 yet. however the 2.6.0 and 2.7.0 jars published to maven are compiled for proto4. So now the generated bytecode for v4 is not compatible with my v3 runtime, as I get the below exception.

I am aware that I asked you to support proto v4 before I (or anyone else probably) really needed it, so my apologies. Do you know what the issue might be? Would your library, compiled for proto3, fix this issue? 

Thanks

```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/openapi_v3/Document.internalGetFieldAccessorTable()Lcom/google/protobuf/GeneratedMessage$FieldAccessorTable; @4: areturn
  Reason:
    Type 'com/google/protobuf/GeneratedMessageV3$FieldAccessorTable' (current frame, stack[0]) is not assignable to 'com/google/protobuf/GeneratedMessage$FieldAccessorTable' (from method signature)
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'org/openapi_v3/Document' }
    stack: { 'com/google/protobuf/GeneratedMessageV3$FieldAccessorTable' }
  Bytecode:
    0000000: 2ab6 0152 b0                           

        at org.openapi_v3.AnnotationsProto.<clinit>(AnnotationsProto.java:32)
        at com.somecorporation.proto.ApiCommon.<clinit>(FinancialApiCommon.java:179)
        at com.somecorporation.proto.v1.DoSomethingRequestProto.internalGetFieldAccessorTable(AuthorizeRequestProto.java:43)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:116)
        at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildAndAdd(TypeSpecificMarshaller.java:137)
        at org.curioswitch.common.protobuf.json.MessageMarshaller$Builder.build(MessageMarshaller.java:494)
        at com.linecorp.armeria.common.grpc.GrpcJsonUtil.jsonMarshaller(GrpcJsonUtil.java:62)
        at com.linecorp.armeria.common.grpc.GrpcJsonMarshallerBuilder.build(GrpcJsonMarshallerBuilder.java:70)
        at com.linecorp.armeria.common.grpc.GrpcJsonMarshaller.of(GrpcJsonMarshaller.java:47)
        at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:196)
        <-->
        at com.linecorp.armeria.server.grpc.FramedGrpcService.getJsonMarshallers(FramedGrpcService.java:111)
        at com.linecorp.armeria.server.grpc.FramedGrpcService.<init>(FramedGrpcService.java:167)
        at com.linecorp.armeria.server.grpc.GrpcServiceBuilder.build(GrpcServiceBuilder.java:1009)
        <-->
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - we have CI workflow running against both latest proto and 3.x so AFAIK there shouldn't be any tie-in caused by this library. Our POM does have to pick a version and we go with the latest as conventional for libraries that target multiple versions (I think) but I think you should be able to force 3.x in your build if you're currently getting the automatic one, e.g. by using a exclusion in maven?

**Comment by C0mbatwombat** [comment]
Ah, thank you. I'll try that.

**Comment by C0mbatwombat** [comment]
Hi @chokoswitch, it worked! Thanks again
